### ISSUE TITLE
I have a pair of question...

### ISSUE THREAD

**Issue by marcodelucia** [pnowy/NativeCriteria#26]
1. Is it possible to get value from a column of type blob in mysql DB?
2. Is the limit clause working for MySql DB?

**Comment by pnowy** [comment]
Answering to your question:

Ad.1. Yes it is possible. I've prepared the BlobTest class within test module. You could see there how to use it. I also released the 2.0.1 where I've added the CriteriaResult.getBlob() methods which returns byte[]. The version will be available soon on maven central (normally it takes a couple of hours).

Ad.2. On that BlobTest class I also had added the 'shouldUseLimitClause' test with limit clause check for MySQL. It works correctly as I checked it on MySQL.

How to run the tests on specific server - please take a look on README within test module.

Hope it helps!

**Comment by marcodelucia** [comment]
Thx for your support. I am now able to retrieve the blob!
I continue to have some problem with the limite clause. My code is:
`NativeCriteria nc = new NativeCriteria(new HibernateQueryProvider(session), tableName, "a");
CriteriaResult criteriaResult = nc.setProjection(NativeExps.projection().addProjection("a.raw_data")).setLimit(limit).criteriaResult();`

**Comment by pnowy** [comment]
Hi,

I afraid that based on provided information I couldn't say what the exact problem is. Unfortunately I cannot recreate it.

Please take a look at BlobTest#shouldUseLimitClause() and try to change the query in the way to cause the problems (I've also tried the projection and it works fine) and make a pull request.

I will also need the:

- you hibernate & MySQL version & MySQL connector version
- could you enable hibernate SQL query log (on spring you could enable it by properties and spring.jpa.show_sql=true) and see what the query is. In my limit case it is:
`Hibernate: SELECT a.id as id898_ FROM address a  limit ?`
- the table structure on which you are trying execute the query and example data

I hope with these information I will could help more!

**Comment by marcodelucia** [comment]
Hi Pnowy,
I tried to run the code you use in BlobTest#shouldUseLimitClause() but nothing changed.
I have changed the log level too, and this is what I can read in the log:

11:06:48,656  WARN DriverManagerConnectionProviderImpl:93 - HHH000402: Using Hibernate built-in connection pool (not for production use!)
11:06:48,656  INFO DriverManagerConnectionProviderImpl:166 - HHH000401: using driver [com.mysql.jdbc.Driver] at URL [jdbc:mysql://localhost:3306/demodb1]
11:06:48,656  INFO DriverManagerConnectionProviderImpl:175 - HHH000046: Connection properties: {user=root, password=****}
11:06:48,656  INFO DriverManagerConnectionProviderImpl:180 - HHH000006: Autocommit mode: false
11:06:48,656  INFO DriverManagerConnectionProviderImpl:102 - HHH000115: Hibernate connection pool size: 1 (min=1)
11:06:49,078  INFO Dialect:145 - HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
11:06:49,078  INFO TransactionFactoryInitiator:62 - HHH000399: Using default transaction strategy (direct JDBC transactions)
11:06:49,078  INFO ASTQueryTranslatorFactory:47 - HHH000397: Using ASTQueryTranslatorFactory
11:06:49,078 TRACE TypeFactory:72 - Scoping types to session factory org.hibernate.internal.SessionFactoryImpl@1349883
11:06:49,219 DEBUG NativeCriteria:633 - NativeCriteria SQL: SELECT a.* FROM 127_0_0_1_2103_0_0_101 a 
11:06:49,307  WARN SqlExceptionHelper:144 - SQL Error: 1064, SQLState: 42000
11:06:49,307 ERROR SqlExceptionHelper:146 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2 a.* FROM 127_0_0_1_2103_0_0_101 a' at line 1
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:80)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:91)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2066)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1863)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1839)
	at org.hibernate.loader.Loader.doQuery(Loader.java:910)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
	at org.hibernate.loader.Loader.doList(Loader.java:2554)
	at org.hibernate.loader.Loader.doList(Loader.java:2540)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
	at org.hibernate.loader.Loader.list(Loader.java:2365)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:353)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1873)
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:311)
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:141)
	at com.github.pnowy.nc.core.hibernate.HibernateNativeQuery.list(HibernateNativeQuery.java:24)
	at com.github.pnowy.nc.core.NativeCriteria.list(NativeCriteria.java:408)
	at com.github.pnowy.nc.core.NativeCriteria.criteriaResult(NativeCriteria.java:317)
	at com.mii.mcs32.databaselayer.hibernate.QueryUtil.getDataRawWithCriteria(QueryUtil.java:156)
	at com.mii.mcs32.databaselayer.hibernate.Test.main(Test.java:90)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2 a.* FROM 127_0_0_1_2103_0_0_101 a' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2825)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2323)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:82)
	... 18 more
java.lang.NullPointerException
	at com.mii.mcs32.databaselayer.hibernate.Test.main(Test.java:91)

My hibernate version is 4.3.8.Final, my mysql connector version is 5.1.27 and my mysql version is 5.6.28.
Thanks again in advance for your support.

Marco

**Comment by marcodelucia** [comment]
Hi Pnowy,
It was my fault, sorry!
I had hsql dialect instead of mysql dialect in my hibernate.cfg.xml.
:-)
Thanks!

**Comment by pnowy** [comment]
Good to know that problem has been fixed!
